# Specify AWS CLI Profile to be Used
aws_profile: default


#### Ansible Paths ####
# Path to ansible config directory
ans_conf_dir: /etc/ansible/
# Path to ansible inventory file
ansible_inv_path: /etc/ansible/hosts/hosts.txt


#### AWS Subnets ####
## These two subnets should have connectivity between then
# For Master Node
master_subnet_id: "subnet-1cae7d43"
# For Worker Nodes
worker_subnet_id: "subnet-1cae7d43"


#### AMI IDs ####
## Recommended To use RedHat Linux
# For Master Node
master_ami_id: "ami-096fda3c22c1c990a"
# For Worker Nodes
worker_ami_id: "ami-096fda3c22c1c990a"


#### Specify Instance Types ####
## Recommended to have more then 1 CPUs for K8s
# For Master Node
master_inst_type: "t2.medium"
# For Worker Nodes
worker_inst_type: "t2.medium"


#### Your Public CIDR ####
# This Public CIDR/IP is allowed through Security Group of Master Node
# So that Master Node can be accessible
#
# If not specified, then by default 0.0.0.0/0 will be allowed
# That is Master Node is vulnerable as it is publically open
pub_cidr: "0.0.0.0/0"


# Port Number for kubernetes KubeAPI Server
kubeapi_port: 6443

# Number of Worker Nodes for k8s cluster
no_of_workers: 2
